### ISSUE TITLE
Informative question

### ISSUE THREAD

**Issue by tranca** [GhostPack/SharpDump#1]
Hi,

This tool collection is an awesome idea, so first of all, thanks for it !

My question is related to the utility of this binary. As it needs to be compiled, dropped on the "target", and acts like Mimikatz but dumps the lsass process first. What's the benefits of using it instead of just using Mimikatz?

Best regards,

**Comment by cnotin** [comment]
It looks like you confuse SharpDump with SafetyKatz.
SharpDump is a generic process dumping tool. SafetyKatz is built on it, and adds the mimikatz feature.

But your question is interesting! @qlemaire asked the [same question](https://bloodhoundhq.slack.com/archives/C20NG2L87/p1532510209000094) on the BloodHound Slack.
One answer explains that with this you don't have to build a VM with the same architecture as the target.

But this approach has drawbacks and mini-dumping LSASS is almost the same as opening it directly with mimikatz. The [blog post](https://posts.specterops.io/ghostpack-d835018c5fc4) states the following but I'm not sure that the last part is true.
> This allows you to extract passwords from a system without having to transport the multi-megabyte minidump file, but prevents the Mimikatz’ specific OpenProcess attach to LSASS.

**Comment by tranca** [comment]
You're absolutely right, I was talking about SafetyKatz!

The problem of building a VM for each architecture is not encountered when running directly Mimikatz on the target (with sekurlsa::logonpasswords), only when you use it with a minidump.

However, I can see the advantages of a smaller binary, when having limitations about data transfer.

Finally, regarding the blog post, if I understand correctly they use MiniDumpWriteDump to dump LSASS instead of the OpenProcess performed by Mimikatz to inject itself in the process.

**Comment by cnotin** [comment]
Hi @tranca, here is @gentilkiwi's opinion on this:
https://twitter.com/gentilkiwi/status/1022386916510060545?s=19

**Comment by gentilkiwi** [comment]
Especially because there is no more injection since 2012...
